### ISSUE TITLE
Websocket steps don't work in ReadyAPI update 2.4.0

### ISSUE THREAD

**Issue by martinhesdahl** [hschott/ready-websocket-plugin#12]
After installing ReadyAPI update 2.4.0 the websocket steps don't work anymore. See stack trace below:
![websockets don t work in 2 4 0](https://user-images.githubusercontent.com/40563047/41842349-d75fb03c-786a-11e8-9fc2-af763b8c0491.jpg)

Could you please help me out? Is there still a jar I have to copy? I already copied all jars I had in the /bin/ext map to the new /bin/ext map of readyapi-2.4.0 but that didn't work. I would like to know if you have the same problem or if I still have to adjust something in my local configurations..

**Comment by NandaRam153** [comment]
This probably need to be updated for newer versions of ReadyApi. Getting the same error and fails.

**Comment by oaxjogi** [comment]
Any chance to get it fixed?

**Comment by oaxjogi** [comment]
I have since 13. July an issue open at SmartBear (RIA-8355) because I run into a similar problem 

> ERROR: An error occurred [com/btr/proxy/selector/direct/NoProxySelector], see error log for details

AFAIK SmartBear is working to integrate WebSocket also directly into SOAP UI but have no ETA when they will have it included. Would be great if @hschott could fix the plugin that we can update to the newer release... I wrote him a note on XING.

**Comment by hschott** [comment]
Issue is related to TYRUS-412. Since Tyrus 1.13 a workaround for HTTP proxy handling is not needed anymore.
I update the plugin to depend on Tyrus 1.13.1. Please check again with version v2.0.8 of the plugin.
Be aware that the released version at GitHub is not signed by Smartbear.

**Comment by oaxjogi** [comment]
Works fine with ReadyAPI 2.5.0. Many thanks!
