### ISSUE TITLE
UI not working in ReadyAPI >3.9.2

### ISSUE THREAD

**Issue by blubdiblah** [hschott/ready-websocket-plugin#15]
For ReadyAPI versions higher than 3.9.2 trying to open a websocket-teststep in the UI fails.

Fixed it for my use by updating the ready-api-ui dependency. (Find the latest one [here](https://rapi.tools.ops.smartbear.io/nexus/content/groups/public/com/smartbear/ready-api-ui/))
```
<dependency>
    <groupId>com.smartbear</groupId>
    <artifactId>ready-api-ui</artifactId>
    <version>3.9.2</version>
    <scope>provided</scope>
</dependency>
```

Renamed few `@Override` Methods.

Changed `appendButtonWithoutLabel(String, ActionListener)` to `addButtonWithoutLabelToTheRight(String, ActionListener)` in method `buildConnectionSection(...)` of class `ConnectedTestStepPanel`

**Comment by hschott** [comment]
Fixed for ReadyAPI 3.53 with Release v2.1.0
