### ISSUE TITLE
Open a websocket connection without sending or receiving a message

### ISSUE THREAD

**Issue by basardaldal** [hschott/ready-websocket-plugin#3]
Is it possible to have an "Open Websocket Connection" test step which would only open the websocket connection without waiting for a message or publishing a message? The reason is, if websocket is used for receiving a message, the client opens the connection first for listening messages, but at that time you do not know if there is going to be a message or not.

**Comment by hschott** [comment]
Sounds interesting. Just to make sure i've got you right: You think of a "only connect" step, without sending or waiting for a message and in case of a successful connect (or if already connected) the test step succeeds?

**Comment by basardaldal** [comment]
Exactly. I think this is a usual behaviour if you are using Websocket for incoming notifications. After you login to a web page, you open the websocket connection for receiving a notification but you do not know when it will come. I see "Receive Websocket Message" step can be used for that too, which firstly opens the connection and then waits for receiving a message but this will add an extra delay while opening the connection which may result with losing the incoming notification.
An example test case scenario could be:
1. Login to web page (REST step)
2. Open Websocket Connection
3. Initiate an action (REST step)
4. Receive Websocket Message
5. Drop websocket connection
6. Logout

**Comment by basardaldal** [comment]
As a workaround, I am using a "Publish Websocket Message" step and sending a dummy text, just to check if the connection can be opened or not.

**Comment by hschott** [comment]
fixed with v2.0.7

**Comment by basardaldal** [comment]
Thanks!
