### ISSUE TITLE
Websocket connections under load test

### ISSUE THREAD

**Issue by basardaldal** [hschott/ready-websocket-plugin#4]
While using the Load Test option in SOAPUI, when each thread wants to open a different websocket connection to the same server but with different URIs, like each URI has a sessionid in it, how does the plugin treat those multiple connections? Even if "Close connection between each request" option is not selected, I think the plugin should still keep a separate connection for each URI. Currently, if I do not select that option, the Load Test fails and I think the reason is multiple threads are trying to use the same connection since the destination IP is the same. I may be wrong in that assumption, could you please clarify?

**Comment by hschott** [comment]
The connection is cached with the connections name as the key. If you dynamically change the URI or query parameters at the URI this will be effective only after a re-connect.
Please use the latest version v2.0.6, since there was a bugfix in this version regarding connection re-use in LoadTests.

**Comment by basardaldal** [comment]
Thanks. I am using 2.0.6.
I use a constant connection name but I use the Server URI as a variable, something like "${#channel}" where a groovy script sets the channel parameter at the beginning of a test case. Here, channel is the full URI like ws://ip_addr/session_id and sessionid changes for each Test Case execution. So, in that case, the websocket connection cache can only be used only within the execution of the same Test Case, right? I mean, if you have multiple Receive/Publish Websocket Message steps in a test case which share the same "channel", they are going to use the same connection but in a Load Test, each Thread and different executions of the same Thread will use different connections. 
Should I also use connection name as a variable?

**Comment by hschott** [comment]
The connection's name i not expanded, which means a variable or expression is not evaluated and transformed into a value.
For the test case you like to run, i recommend to use the 'Close Connections: [ ] between each request' option in the LoadTest Options.

**Comment by basardaldal** [comment]
"Close connections between each request" will cause each websocket step in a test case to open a new connection, right? That means, there is no connection reuse.

**Comment by hschott** [comment]
"Close connections between each request" will cause a close of a connection after each TestCase run . Every TestStep in a TestCase will re-use a connection opened in a TestStep before in the same TestCase.

**Comment by basardaldal** [comment]
Are you saying this for websocket plugin? For HTTP requests (SOAP or REST), I think this is not the way it works; if you have multiple HTTP requests in a test case, each of them will open a new connection before sending the request and and close it after receiving the response.

**Comment by hschott** [comment]
Yes, this is a special behavior for websocket, due to the fact that this is not a request/response pattern like REST or SOAP.

**Comment by basardaldal** [comment]
I believe it would be better to change this logic. The parameter (Close connection after each request) is asking for closing the connection after each request, so it should cover the websocket steps as well - it should not make an exception for websocket connections, otherwise this is going to cause confusion and wrong assumptions and you will need to explain this exception to everyone who uses this plugin.

I believe that the default behaviour for websocket connections should be using the same connection until a "Drop Websocket Connection" test step is called or the execution of the Test Case is ended (assuming the server definition is same for all steps). If "Close Connection after each Request" parameter is selected then this behaviour should be overridden - Each Receive / Publish test step should close the connection after it is done. This will make the usage of the parameter consistent with HTTP based requests. 

Just my 2 cents...

**Comment by hschott** [comment]
Thank you for sharing your opinion.
For websocket connections a 'request' spans from connect until disconnect and it's lifetime can not easily be bound to SoapUI TestSteps. 
Unfortunately plugin developers can not customize or extends the LoadTest options dialog. Thus i have take what is given and document the meaning.
With the implemented logic i wanted to span the lifetime of a websocket connection over the hole LoadTest run. For one reason, i don't wanted to loadtest the websocket handshake but the message stream.
