### ISSUE TITLE
Configurable Delay or Wait Option in Drop Websocket Teststep

### ISSUE THREAD

**Issue by alcalda** [hschott/ready-websocket-plugin#6]
I observed that the ready-websocket-plugin client often sends a TCP [RST, ACK] packet just after the reception of the ACK to the websocket close message without waiting for the CLOSE message from the server. As the tested server want's to send it's own answer to the CLOSE message this fails, since the TCP connection has been reset by the client.

I would like to see either an option to wait for the server's answer on Websocket CLOSE messages with a configurable timeout before clearing the websocket session (to give the server more time to send it's answer).

**Comment by hschott** [comment]
ready-websocket-plugin uses the Tyrus JDK client. Tyrus is the reference implementation of JSR-356, which designs an Java API around RFC 6455.
RFC 6455 defines a Closing Handshake in the way you expect the CLOSE to be.

You may file an issue to the Tyrus project and link it here.
