### ISSUE TITLE
Option to assert a Receive Websocket Message timeout as Pass

### ISSUE THREAD

**Issue by alcalda** [hschott/ready-websocket-plugin#7]
I use websockets for a subscription to resources of the DUT. In a case of a changed resource the DUT sends websocket events to inform the client about the change of the resource.

After the unsubscription of the resource it is expected to NOT receive websocket events from the target regarding this specific resource.

I would like to have the possibility to assert the absence within a timeout period of an websocket event as Pass. In the moment the teststep is marked as fail.

**Comment by hschott** [comment]
That would be a lot of effort to negate matcher logic. I recommend not to test for the absence of something. Try to change the subscription and match for changed messages.

**Comment by alcalda** [comment]
Alternatively Using pytest and regular Python websocket clients for some tests. It is possible with this other approach to test for the raise of a Websocket Timeout Exception. Could this be a way to reduce the effort?

**Comment by hschott** [comment]
Sorry, but i do not understand where the reduction should take place. This project is programmed in Java and not in Python. The plugin is based on the given SoapUI framework, where btw. match negation is also not possible, and is based on Tyrus Websocket client.
