### ISSUE TITLE
Does the plug-in supports capturing real time streaming data?

### ISSUE THREAD

**Issue by vijay-gupta** [hschott/ready-websocket-plugin#9]
Hi,

Just wanted to know if the plug-in supports capturing real time streaming data?

I used the plug-in in Ready API and it is only capturing first response and not the streaming data for a specific time period (for instance: I want to capture the real time streaming data for about 3 minutes). I was wondering if it is possible using the plug-in?

**Comment by AsheeshGareeb** [comment]
I also want to know if this is supported !!

**Comment by hschott** [comment]
You may achieve this by configuring a assertion that does not match any of the incoming fragments plus setting a timeout accordingly your needs.

**Comment by vijay-gupta** [comment]
Thanks Holger. We will try this out and let you know
